// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table Sensor (applicationId:string, deviceId:string, enqueuedTime:datetime, ConnectionStatus:long, EndDatetime:datetime, EnergyAmountkWh:dynamic, PowerReading:dynamic, StartDatetime:datetime, VoltageReading:dynamic, enrichments:dynamic) 
