name: Create PR TF Plan comment

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}
      FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}
      FABRIC_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}
      FABRIC_USE_OIDC: false
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_USE_OIDC: true
      WORKING_DIRECTORY: "./tf"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: '${{ env.WORKING_DIRECTORY }}'
          backend_config: "resource_group_name=${{ vars.TERRAFORM_BACKEND_RG }} storage_account_name=${{ secrets.TERRAFORM_BACKEND_SA }} container_name=${{ vars.TERRAFORM_BACKEND_CONTAINER }} key=${{ vars.TERRAFORM_BACKEND_KEY }}"
          variables: |
            tenant_id = "${{ secrets.FABRIC_TENANT_ID }}"
            client_id = "${{ secrets.FABRIC_CLIENT_ID }}"
            client_secret = "${{ secrets.FABRIC_CLIENT_SECRET }}"
            admin_user = "${{ secrets.ADMIN_USER }}"
            admin_user2 = "${{ secrets.ADMIN_USER2 }}"
            subscription_id = "${{ secrets.ARM_SUBSCRIPTION_ID }}"

